### ISSUE TITLE
Use container image

### ISSUE THREAD

**Issue by niraj8** [medlypharmacy/create-pr-action#5]
Currently the action builds the image on each run, we can reduce the time it takes to become available.

We can refer s3-artifacts-action workflows to do this

**Comment by Poorva17** [comment]
Thanks @niraj8 for pointing this out. I will update here once fix is pushed :)

**Comment by Poorva17** [comment]
@niraj8 can you please review https://github.com/medlypharmacy/create-pr-action/pull/4

**Comment by Poorva17** [comment]
This is fixed. Please refer to https://github.com/medlypharmacy/create-pr-action/pull/4 for details. Thanks @niraj8
